In [11]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [12]:
#2. Print the NUMPY version and the configuration.
print(np.version.version)

1.16.2


In [13]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a= np.random.random((2,3,5)) # 2 matrix, 3 rows, 5 columns
print(a)
a1= np.random.rand(2,3,5)
print(a1)
a2= np.arange(30).reshape(2,3,5)
print(a2)

[[[0.21748304 0.97782733 0.54156085 0.47822234 0.67206088]
  [0.54969501 0.63481127 0.32103937 0.57500187 0.03951756]
  [0.86925643 0.357429   0.42915794 0.96395175 0.21379654]]

 [[0.15958102 0.30051363 0.68925611 0.47190464 0.48603932]
  [0.47822462 0.6684856  0.08214674 0.44527539 0.49615737]
  [0.046336   0.26410712 0.75034966 0.12577416 0.36954686]]]
[[[0.90232765 0.04097446 0.49296829 0.29034877 0.71441382]
  [0.10790237 0.88198533 0.29142487 0.4871262  0.50724075]
  [0.59690225 0.42651503 0.38012844 0.91364082 0.66162571]]

 [[0.85441891 0.37255242 0.80754698 0.46506112 0.64494712]
  [0.85183535 0.27531776 0.75348782 0.70407767 0.10078206]
  [0.97782525 0.04041133 0.50668231 0.36572665 0.66840331]]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [14]:
#4. Print a.
print(a)

[[[0.21748304 0.97782733 0.54156085 0.47822234 0.67206088]
  [0.54969501 0.63481127 0.32103937 0.57500187 0.03951756]
  [0.86925643 0.357429   0.42915794 0.96395175 0.21379654]]

 [[0.15958102 0.30051363 0.68925611 0.47190464 0.48603932]
  [0.47822462 0.6684856  0.08214674 0.44527539 0.49615737]
  [0.046336   0.26410712 0.75034966 0.12577416 0.36954686]]]


In [15]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b= np.ones((5,2,3))

In [16]:
#6. Print b.
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [17]:
#7. Do a and b have the same size? How do you prove that in Python code?

print(np.size(a) == np.size(b))


True


In [18]:
#8. Are you able to add a and b? Why or why not?
a+b
#they have the same size & don't have the same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [ ]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). 
#Assign the transposed array to varialbe "c".
c= np.transpose(b).reshape(2,3,5)
print(np.shape(c))
print(c)

In [ ]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d= a+c
print(d)
#Because a & c have the same shape


In [ ]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a)
print('Separation')
print(d)

# added 1 to each value of the matrix

In [ ]:
#12. Multiply a and c. Assign the result to e.
e= a*c

print(e)


In [ ]:
#13. Does e equal to a? Why or why not?

#yes e is equal to a, because we multiplied each value of tha matrix by 1 

In [ ]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

In [ ]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f= np.empty((2,3,5))
print(f)

In [19]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d_min<d[i][j][k] <d_mean:
                 f[i][j][k]  =25
            elif d_mean<d[i][j][k]<d_max:
                f[i][j][k]  =75
            elif d[i][j][k] == d_mean:
                 f[i][j][k] = 50
            elif d[i][j][k] == d_min:
                f[i][j][k] =0
            elif d[i][j][k]==d_max:
                f[i][j][k] =100


print(f)
#from float to string
#f=np.char.mod(%s,a)
#change values
#f[f=='0.2'] = 'A'
#change values
#np.where(f=='0.2', 'B',f)

NameError: name 'd_min' is not defined

In [ ]:
print(np.shape(d))
print(np.shape(f))
d[1][2][3]

In [ ]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""
print(d)
print(f)
# yes i have my expected f

In [ ]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

f= f.astype("object")
for i in range(2): # we can replace 2 by np.shape(f)[0]
    for j in range(3):#we can replace 2 by np.shape(f)[1]
        for k in range(5): #we can replace 2 by np.shape(f)[2]          
            if d_mean>d[i][j][k] >d_min:
                f[i][j][k]  ="A"
            elif d_max>d[i][j][k]>d_mean:
                f[i][j][k]  ="B"
            elif d[i][j][k] == d_mean:
                f[i][j][k] = "C"
            elif d[i][j][k] == d_min:
                f[i][j][k] ="D"
            elif d[i][j][k]==d_max:
                f[i][j][k] ="E"
print(f)