In [2]:
import pandas as pd

In [4]:
df=pd.read_csv('acs2015_county_data.csv')

In [5]:
import numpy as np

print(np.random.randint(37))
print(np.random.randint(37))


34
36


In [6]:
df.iloc[:5,[9,18]]

Native  ChildPoverty
0     0.4          18.6
1     0.6          19.2
2     0.2          45.3
3     0.4          27.9
4     0.3          27.2

In [7]:
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest
select = SelectKBest(chi2,k=6)
X = df.iloc[:,9:18]
y = df.iloc[:,19]
print(X.shape,y.shape)


(3220, 9) (3220,)


In [10]:
X[pd.isnull(X).any(axis=1)].index[0]

2673

In [11]:
y.drop(X[pd.isnull(X).any(axis=1)].index[0], inplace=True)

X.dropna(inplace=True)


In [12]:
print(X.shape,y.shape)

(3219, 9) (3219,)


In [19]:
X_new=select.fit_transform(X,y)
X_new.shape

ValueError: Unknown label type: (array([33.2, 33.1, 26.8, ..., 23.6, 25.9, 28.1]),)

In [14]:
[X[i].unique() for i in X.columns]

[array([ 0.4,  0.6,  0.2,  0.3,  1.2,  0.1,  0. ,  0.7,  0.8,  0.5,  1.1,
         3.2,  5.4,  1.3,  8.1, 29. , 12.9,  6.3, 80.6,  3.5, 71.7,  5.7,
         6.4, 32.4, 11.8,  7.3, 13.6, 13.3, 87.4, 67.6,  5.1, 69.8, 47.4,
        81.5,  5.9, 40.3,  5. , 10.5, 14.8, 17.3, 32.2, 69.9, 26. , 15.1,
         2.8, 12.2,  1.6,  1.7, 43.1,  2.4,  4.7,  1. ,  1.4,  0.9,  1.9,
        19.4,  1.8,  4.8,  4.6, 10.2,  3. ,  2.3,  3.4,  2.2,  2.7,  1.5,
         2.1, 11.3,  3.7,  4. ,  2.6,  8.9,  3.8,  3.6,  6.5,  7.4,  5.3,
         2. ,  7.6,  4.5,  6.7, 15.7,  7. , 20. , 10.6,  8.5,  3.3, 39.2,
         5.8, 15.3, 62.7, 48. ,  4.1, 19.2, 63.1, 22.3, 23.3,  2.5,  9.4,
        14.3, 55.5, 33.6,  4.4, 10.1,  2.9,  8.8,  9.1, 55.1,  3.9, 16.7,
        38.5, 72.3,  6.2, 14. , 11.9, 36.3,  9.8,  7.2,  7.8,  8.4, 37.6,
        10.4, 26.1, 54.5,  9.9,  4.2, 17.2,  7.1, 26.5,  4.3,  9.6, 77.2,
        79.4,  4.9, 14.4, 21.8,  8. , 32.1, 12. , 11.5, 18.5, 20.4,  6. ,
        16.4, 17.9, 14.9,  6.9, 13.8, 

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3220 entries, 0 to 3219
Data columns (total 37 columns):
CensusId           3220 non-null int64
State              3220 non-null object
County             3220 non-null object
TotalPop           3220 non-null int64
Men                3220 non-null int64
Women              3220 non-null int64
Hispanic           3220 non-null float64
White              3220 non-null float64
Black              3220 non-null float64
Native             3220 non-null float64
Asian              3220 non-null float64
Pacific            3220 non-null float64
Citizen            3220 non-null int64
Income             3219 non-null float64
IncomeErr          3219 non-null float64
IncomePerCap       3220 non-null int64
IncomePerCapErr    3220 non-null int64
Poverty            3220 non-null float64
ChildPoverty       3219 non-null float64
Professional       3220 non-null float64
Service            3220 non-null float64
Office             3220 non-null float64
Constru

In [17]:
from statsmodels.regression.linear_model import OLS

import statsmodels.api as sm
X=sm.add_constant(X)
model=sm.OLS(y,X)
results=model.fit()
results.summary()

/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:           Professional   R-squared:                       0.507
Model:                            OLS   Adj. R-squared:                  0.506
Method:                 Least Squares   F-statistic:                     366.6
Date:                Tue, 25 Jun 2019   Prob (F-statistic):               0.00
Time:                        16:58:07   Log-Likelihood:                -9388.1
No. Observations:                3219   AIC:                         1.880e+04
Df Residuals:                    3209   BIC:                         1.886e+04
Df Model:                           9                                         
Covariance Type:            nonrobust                                         
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const               4.5162      0.822      5.494      0.000       2.904       6.128
Native              0.0918      0.011      8.181      0.000       0.070       0.114
Asian               0.1547      0.041      3.740      0.000       0.074       0.236
Pacific            -0.7804      0.118     -6.611      0.000      -1.012      -0.549
Citizen          1.337e-06   4.57e-07      2.924      0.003    4.41e-07    2.23e-06
Income           4.349e-05    1.6e-05      2.726      0.006    1.22e-05    7.48e-05
IncomeErr       -3.289e-05   5.98e-05     -0.550      0.582      -0.000    8.43e-05
IncomePerCap        0.0008   3.16e-05     26.042      0.000       0.001       0.001
IncomePerCapErr  9.362e-05      0.000      0.810      0.418      -0.000       0.000
Poverty             0.2475      0.017     14.772      0.000       0.215       0.280
==============================================================================
Omnibus:                      266.899   Durbin-Watson:                   1.760
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1220.420
Skew:                           0.268   Prob(JB):                    9.75e-266
Kurtosis:                       5.968   Cond. No.                     2.27e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.27e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [18]:
from sklearn.linear_model import Ridge

model=Ridge(alpha=1.0)
model.fit(X,y)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [20]:
model.intercept_

4.516037304773494

In [22]:
model.coef_

array([ 0.00000000e+00,  9.17579132e-02,  1.54564315e-01, -7.79871751e-01,
        1.33724639e-06,  4.34992256e-05, -3.28936533e-05,  8.22788117e-04,
        9.35729856e-05,  2.47499295e-01])

In [23]:
from sklearn.linear_model import Ridge

model=Ridge(alpha=0.8)
model.fit(X,y)

Ridge(alpha=0.8, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [24]:
model.intercept_

4.516065267065194

In [25]:
model.coef_

array([ 0.00000000e+00,  9.17583171e-02,  1.54581448e-01, -7.79982875e-01,
        1.33718599e-06,  4.34981593e-05, -3.28926113e-05,  8.22788295e-04,
        9.35816831e-05,  2.47498942e-01])

In [26]:
from sklearn.linear_model import Lasso

model=Lasso(alpha=1.0)
model.fit(X,y)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [27]:
model.coef_

array([ 0.00000000e+00,  7.42346228e-02,  0.00000000e+00, -0.00000000e+00,
        2.04132787e-06,  4.61855466e-05, -4.42743651e-05,  8.04203083e-04,
        2.06463305e-05,  2.21959512e-01])

In [28]:
model.score(X,y)

0.49871839621728264