# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [47]:
# Import your libraries:
import pandas as pd
import numpy as np

# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function.

In [48]:
# Your code here:
from sklearn import datasets
diabetes = datasets.load_diabetes()

Let's explore this variable by looking at the different attributes. Do this by looking at the `keys()` of this variable.

In [49]:
# Your code here:
diabetes.keys()

dict_keys(['data', 'target', 'DESCR', 'feature_names', 'data_filename', 'target_filename'])

The next step is to read the description of the dataset. Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable

In [50]:
# Your code here:
print(diabetes.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - Age
      - Sex
      - Body mass index
      - Average blood pressure
      - S1
      - S2
      - S3
      - S4
      - S5
      - S6

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
http://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Brad

What are the variables in this dataset according to the description? List them in the markdown cell below

#### Enter your answer here:




Now explore the data. Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). In the cell below find the shape of the numpy array contained in the data portion of the diabetes variable.

In [51]:
# Your code here:
#diabetes.target.shape
diabetes.data.shape

(442, 10)

In [52]:
diabetes.data.shape

(442, 10)

# Challenge 2 - Perform Supervised Learning on the Dataset

#### The data has already been split to predictor and response variables. The response variable is in the `target` portion of the variable. 

Given this information, let's apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset. In the cell below, import the linear regression class from sklearn. 

In [53]:
# Your code here:
from sklearn.linear_model import LinearRegression


Initialize the model in the variable `diabetes_model`

In [54]:
# Your code here:
diabetes_model = LinearRegression()

In the cell below, fit the model and print the intercept and coefficients of the model. 

In [55]:
diabetes.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [56]:
# Your code here:

diabetes_reg= diabetes_model.fit(diabetes.data, diabetes.target)
diabetes_reg.intercept_
diabetes_reg.coef_

array([ -10.01219782, -239.81908937,  519.83978679,  324.39042769,
       -792.18416163,  476.74583782,  101.04457032,  177.06417623,
        751.27932109,   67.62538639])

# Bonus Challenge 1 - Conduct a Hypothesis Test on the Model

Once we have generated a linear model, we can test each coefficient using a t-test to see whether the confidence interval for the variable contains zero. We can also perform an overall F test to check whether at least one coefficient is significantly different from zero. 

Refer to the resource in this [link](https://onlinecourses.science.psu.edu/stat501/node/297/) for more details and perform the t-tests for the model above. Additionally, interpret the results and list coefficients are significantly different from zero.


Hint: use the statsmodels package.

Your result should look similar to this:

![ols](../ols-results.png)

In [57]:
# Your code here:



# Challenge 2 - Peform Supervised Learning on a Pandas Dataframe

Now that we have looked at data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [58]:
# Your code here:

auto = pd.read_csv('../auto-mpg.csv')

Look at the first 5 rows using the `head()` function:

In [59]:
# Your code here:

auto.head()

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year                       car_name  
0          70  \t"chevrolet chevelle malibu"  
1          70          \t"buick skylark 320"  
2          70         \t"plymouth satellite"  
3          70              \t"amc rebel sst"  
4          70                \t"ford torino"

Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [60]:
# Your code here:
auto.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
mpg             398 non-null float64
cylinders       398 non-null int64
displacement    398 non-null float64
horse_power     392 non-null float64
weight          398 non-null int64
acceleration    398 non-null float64
model_year      398 non-null int64
car_name        398 non-null object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB


What is the newest model year and the oldest model year?

In [61]:
# Your code here:
print(f'Newest model year:', auto["model_year"].max())
print(f'Oldest model year:',auto["model_year"].min())


Newest model year: 82
Oldest model year: 70


Check the dataset for missing values and remove all rows containing at least one missing value.

In [62]:
# Your code here:
auto=auto.dropna()

Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [65]:
# Your code here:
auto.cylinders.value_counts()
#5 possible values

4    199
8    103
6     83
3      4
5      3
Name: cylinders, dtype: int64

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

In [68]:
# Import the necessary function
#auto.drop('car_name',axis=1,inplace=True)
auto.head()

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year  
0          70  
1          70  
2          70  
3          70  
4          70

In [91]:
# Your code here:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(auto.iloc[:,1:], auto.mpg, test_size = 1/5, random_state = 0)


Now we will the dataset that we processed and peform linear regression on this data to predict the mpg for each vehicle. Initialize the model in the cell below.

In [93]:
# Your code here:

auto_model = LinearRegression()

Next, fit the model in the cell below.

In [94]:
# Your code here:

auto_reg= auto_model.fit(X_train,y_train)
auto_reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

# Challenge 3 - Evaluate the Model

the r squared score of a model tells us how much variation is explained by the model. In a typical dataset, most observations differ from the mean. When we create a model, we are trying to generate an equation that will tell us by how much each observation will differ from the mean. Obviously, the vast majority of models are not perfect. They can only predict some of the variation from the mean but not all of it. We attribute the rest of the difference between the actual value and the mean to random error. We would like random error to explain the as little as possible of the variation. This is why the r squared score is an important metric.

In the next cell, compute the r squared score of the model. Do this by first computing the predicted values and assign them to `y_pred`.

In [95]:
# Import the necessary function:



In [96]:
# Your code here:
auto_model.score(X_test, y_test)

0.8088938602131776

#### Our next step is to evaluate the model using the test data. We would like to ensure that our model is not overfitting the data. This means that our model will not be able to generalize well outside of the training data.

In the cell below, use the model to generate the predicted values for the training data and assign them to `y_test_pred`. Compute the r squared score for the test data by comparing the oberserved `y_test` data and the predicted `y_test_pred`.

In [106]:
# Your code here:
y_test_pred = auto_model.predict(X_test)
y_test_pred

array([27.2734488 , 26.39876978, 10.42252581, 33.27790508, 32.10715834,
       23.56602679, 33.39010024, 25.22520627, 21.04089856, 26.21896028,
       27.77119508, 13.78751344, 25.86593777,  7.73880184, 16.46329411,
       31.95620078, 26.06215132, 12.90114079, 25.8122899 , 27.84664443,
       21.03314128, 18.01668321, 24.96318098, 27.98486373, 31.6663643 ,
       11.22423903, 29.48433768, 26.577297  , 23.29989653, 15.28746665,
       21.74138222, 29.62570762, 23.81898103, 28.45447238, 22.30105527,
       28.0986024 , 28.03323823, 11.20496228, 14.91127216,  9.98867521,
       14.05432369, 33.52183042, 29.42816146, 13.77167009, 30.86021155,
       15.08521001, 30.94817919, 10.29393833, 17.65087133, 22.55535459,
       26.53326636, 15.00849899,  9.57972967, 24.07778446, 31.5200505 ,
       25.80677086, 26.58785346, 20.86650382, 30.70881792, 25.65543998,
       19.83477092, 27.54228219, 31.21990996,  9.9601349 , 25.88345359,
       16.88103074, 10.08934194, 30.37204218, 21.093325  , 32.43

# Challenge 4 - Improve the Model Fit

While the most common way to improve the fit of a model is by using regularization, there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [111]:
# Your code here:

X_train09, X_test09, y_train09, y_test09 = train_test_split(auto.iloc[:,1:], auto.mpg, test_size = 0.1, random_state = 0)


Initialize a new model. Name this model `auto_model09`. Fit the model to the new sample data.

In [112]:
# Your code here:
auto_model09 = LinearRegression()


Compute the predicted values and r squared score for our new model and new sample data.

In [113]:

# Your code here:

auto_reg= auto_model09.fit(X_train09,y_train09)

y_pred09 = auto_model09.predict(X_test09)
y_pred09


array([27.37940156, 26.44699558, 10.50949872, 33.37000007, 32.14605283,
       23.59390225, 33.41459259, 25.19041908, 21.09375031, 26.24874963,
       27.79145228, 13.90181008, 25.93272572,  7.80221772, 16.52162445,
       32.05673715, 26.15054855, 12.98449403, 25.90318871, 27.91271581,
       21.14352417, 18.03148365, 24.97200181, 28.04478784, 31.76465585,
       11.33697388, 29.57613079, 26.65766883, 23.34976162, 15.41585   ,
       21.86478721, 29.6570309 , 23.85763807, 28.54339197, 22.3720656 ,
       28.17895094, 28.0627143 , 11.29910767, 15.01165998, 10.13438036])

Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

In [114]:
# Your code here:

auto_model.score(X_test09, y_test09)

0.7971768846093388

In [128]:


df=pd.DataFrame()
df['y pred']=y_pred
df['y test']=y_test

df

y pred  y test
0   29.642645     NaN
1   25.035719    15.0
2   12.054385     NaN
3   30.093150     NaN
4   30.166413     NaN
5   22.595502    15.0
6   31.522701    14.0
7   24.044523    14.0
8   22.924362     NaN
9   28.778038     NaN
10  32.368090    15.0
11  11.710101     NaN
12  25.828217     NaN
13   9.306466     NaN
14  12.940725     NaN
15  29.163225    22.0
16  24.509001     NaN
17  14.632339     NaN
18  28.434281     NaN
19  26.183228     NaN
20  20.526861    25.0
21  19.552605     NaN
22  28.094995     NaN
23  23.324274     NaN
24  29.536193     NaN
25  13.218079     NaN
26  26.263562    10.0
27  25.858895     NaN
28  23.921092     NaN
29  16.770389     NaN
..        ...     ...
49  24.567754     NaN
50  28.927304     NaN
51  16.807293     NaN
52  11.276248     NaN
53  28.632291    31.0
54  29.318596     NaN
55  23.391493    27.0
56  23.473314    26.0
57  21.007931     NaN
58  32.660549     NaN
59  28.962520     NaN
60  24.436056    20.0
61  29.849000    21.0
62  30.623838     NaN
63  11.329454     NaN
64  29.834160     NaN
65  18.156966    14.0
66  10.817571    17.0
67  26.604476     NaN
68  26.325439     NaN
69  30.537860    12.0
70  32.286641     NaN
71  29.919694     NaN
72  17.332804     NaN
73  14.386343     NaN
74  24.061664     NaN
75  14.198275    14.0
76  31.455435     NaN
77  18.597528    22.0
78  30.788949     NaN

[79 rows x 2 columns]

# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

In [200]:
# Your code here:



Fit the model and print the ranking

In [201]:
# Your code here:



Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_test_reduced`, `y_train_reduced`. Use an 80% split.

In [202]:
# Your code here:



Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [203]:
# Your code here: 

