In [7]:
import numpy as np

a = np.random.random((2,2))
b = np.random.random((4,3,2))
c = np.random.random((5,4,3,2))


In [8]:
print(a)
print(a[0])
print(type(a))

[[0.32364593 0.68449856]
 [0.280965   0.14553225]]
[0.32364593 0.68449856]
<class 'numpy.ndarray'>


In [10]:
print(c)
print(c[0])

# Second subgroup of the first group
print(c[0,1])


# Third row of the second subgroup
print(c[0,1,2])


# Fourth column of the second subgroup
print(c[0,1,:,3])


# Value in the third row and fourth column of the second subgroup
print(c[0,1,2,3])



[[[[0.52558522 0.94677312]
   [0.96714455 0.34898359]
   [0.22326095 0.59740716]]

  [[0.75053938 0.46908738]
   [0.04138699 0.78910967]
   [0.57662911 0.37407395]]

  [[0.08736732 0.3149488 ]
   [0.6163111  0.37284948]
   [0.05334812 0.45447186]]

  [[0.29182125 0.12943794]
   [0.7611158  0.93809568]
   [0.66508481 0.35033899]]]


 [[[0.29492607 0.16377423]
   [0.08639648 0.4273913 ]
   [0.36545099 0.85951061]]

  [[0.53844163 0.28538406]
   [0.64427097 0.19478549]
   [0.37027196 0.73217239]]

  [[0.09852564 0.08745648]
   [0.11138441 0.61305727]
   [0.00469943 0.51345999]]

  [[0.58347651 0.24425922]
   [0.07593563 0.89078314]
   [0.88909876 0.22136743]]]


 [[[0.80703752 0.50818447]
   [0.00184972 0.55718852]
   [0.76484505 0.88177737]]

  [[0.21756102 0.46186769]
   [0.58404404 0.07769374]
   [0.14910499 0.17146499]]

  [[0.61965328 0.96330202]
   [0.80930312 0.55904861]
   [0.59231508 0.00496291]]

  [[0.65833618 0.53689377]
   [0.05799891 0.08396049]
   [0.30945781 0.80543949]]]


IndexError: index 3 is out of bounds for axis 3 with size 2

In [17]:
np.sum(a)
print(a)
print(a.sum())
print(a.sum(axis=1)) # sum of rows
print(a.sum(axis=0)) # sum of columns
print(b.mean(axis=0))

[[0.32364593 0.68449856]
 [0.280965   0.14553225]]
1.4346417392876942
[1.00814449 0.42649725]
[0.60461092 0.83003082]
[[0.49895281 0.57528854]
 [0.40115816 0.52886714]
 [0.38046828 0.67149758]]


In [18]:
b+2

array([[[2.02161661, 2.3948505 ],
        [2.41332073, 2.93682207],
        [2.35593926, 2.4606152 ]],

       [[2.89489774, 2.9101928 ],
        [2.77186233, 2.93726365],
        [2.86276213, 2.7128487 ]],

       [[2.2483895 , 2.43817682],
        [2.09071176, 2.12337415],
        [2.03890093, 2.71108488]],

       [[2.8309074 , 2.55793401],
        [2.3287378 , 2.11800867],
        [2.2642708 , 2.80144153]]])

In [19]:
b-1

array([[[-0.97838339, -0.6051495 ],
        [-0.58667927, -0.06317793],
        [-0.64406074, -0.5393848 ]],

       [[-0.10510226, -0.0898072 ],
        [-0.22813767, -0.06273635],
        [-0.13723787, -0.2871513 ]],

       [[-0.7516105 , -0.56182318],
        [-0.90928824, -0.87662585],
        [-0.96109907, -0.28891512]],

       [[-0.1690926 , -0.44206599],
        [-0.6712622 , -0.88199133],
        [-0.7357292 , -0.19855847]]])

In [20]:
a = np.random.random((2,2))
b = np.random.random((2,2))

In [21]:
a,b

(array([[0.98859436, 0.5155521 ],
        [0.05053338, 0.7398575 ]]), array([[0.03313981, 0.48813155],
        [0.27513593, 0.58748815]]))

In [22]:
a+b

array([[1.02173417, 1.00368365],
       [0.32566931, 1.32734564]])

In [23]:
np.add(a,b)

array([[1.02173417, 1.00368365],
       [0.32566931, 1.32734564]])

In [24]:
np.add(a,-b)

array([[ 0.95545454,  0.02742055],
       [-0.22460255,  0.15236935]])

In [34]:
np.subtract(a,b)

array([[ 0.95545454,  0.02742055],
       [-0.22460255,  0.15236935]])

In [26]:
np.multiply(a,b)

array([[0.03276183, 0.25165725],
       [0.01390355, 0.43465751]])

In [27]:
a*b 

array([[0.03276183, 0.25165725],
       [0.01390355, 0.43465751]])

In [31]:
b*a #multiplication element by element

array([[0.03276183, 0.25165725],
       [0.01390355, 0.43465751]])

In [28]:
np.matmul(a,b)

array([[0.17460874, 0.78544485],
       [0.20523605, 0.45932445]])

In [30]:
np.matmul(b,a) # for matrix

array([[0.05742877, 0.37823309],
       [0.30168559, 0.57650442]])

In [33]:
np.divide(a,b) #divide element by element

array([[29.83101664,  1.05617451],
       [ 0.18366697,  1.25935732]])

In [35]:
np.pi

3.141592653589793

In [36]:
np.e

2.718281828459045

# Library OS

In [37]:
import os

os.getcwd()
os.chdir()
os.path.join()
os.makedirs()

#open function
open(file,mode)
mode:  "r": read
        "a" append
        "w" write
        "x"  create
        "t"  for texte
        "binary" for images

Add and read a texte
f.write
f.read